// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfp4tRM_5KFx7rVsMplXhgG3aN-hoXzQY',
    appId: '1:456509783979:web:c8e891c3af0771282b5cee',
    messagingSenderId: '456509783979',
    projectId: 'squadseeker-8f211',
    authDomain: 'squadseeker-8f211.firebaseapp.com',
    storageBucket: 'squadseeker-8f211.appspot.com',
    measurementId: 'G-LJFMJSHDQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZM31uQgU5EV4mO12SUNBzhYjnqItGw8',
    appId: '1:456509783979:android:9a60561da1d591542b5cee',
    messagingSenderId: '456509783979',
    projectId: 'squadseeker-8f211',
    storageBucket: 'squadseeker-8f211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS9E50VEo3JWp1LDR9NPmary1YCPiptVw',
    appId: '1:456509783979:ios:f7668b26eea9773b2b5cee',
    messagingSenderId: '456509783979',
    projectId: 'squadseeker-8f211',
    storageBucket: 'squadseeker-8f211.appspot.com',
    iosBundleId: 'com.davidshahi.squadSeeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS9E50VEo3JWp1LDR9NPmary1YCPiptVw',
    appId: '1:456509783979:ios:ebb575b817e71d912b5cee',
    messagingSenderId: '456509783979',
    projectId: 'squadseeker-8f211',
    storageBucket: 'squadseeker-8f211.appspot.com',
    iosBundleId: 'com.davidshahi.squadSeeker.RunnerTests',
  );
}
